name: Kernel Decompiler Pro
on:
  push:
    branches: [ main ]
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  decompile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar Python y dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk-headless python3-pip
          pip install vmlinux-to-elf

      - name: Instalar Ghidra (Headless)
        run: |
          wget https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_11.0.1_build/ghidra_11.0.1_PUBLIC_20240130.zip
          unzip -q ghidra_11.0.1_PUBLIC_20240130.zip

      - name: Convertir Binario a ELF (Recuperar Estructura)
        run: |
          # Asumiendo que tu archivo se llama 'kernel' en el repo
          vmlinux-to-elf kernel kernel_estructurado.elf || echo "No se pudo recuperar símbolos, se usará binario plano"

      - name: Ejecutar Análisis de Ghidra
        run: |
          ./ghidra_11.0.1_PUBLIC/support/analyzeHeadless . ProyectoKernel \
          -import kernel_estructurado.elf \
          -processor ARM64:LE:64:v8a \
          -postScript Decompile.py # Necesitarás este script en tu repo

      - name: Subir Código Reconstruido
        uses: actions/upload-artifact@v4
        with:
          name: Kernel_Source_C
          path: ./output_code/