name: RemoteDesktop_Ultra_Fast

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Pega SOLO el código (lo que está entre comillas en --code=)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Instalación Relámpago
        run: |
          sudo apt-get update
          # Instalamos solo lo mínimo necesario para que sea rápido
          sudo apt-get install -y xfce4 xfce4-terminal desktop-base
          wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
          sudo apt-get install -y ./chrome-remote-desktop_current_amd64.deb
          sudo apt-get install -f -y
      
      - name: Iniciando Acceso Remoto
        run: |
          DISPLAY= /opt/google/chrome-remote-desktop/start-host \
          --code="${{ github.event.inputs.authcode }}" \
          --redirect-url="https://remotedesktop.google.com/_/oauthredirect" \
          --name=GitHub-Runner \
          --pin=123456
          
      - name: Mantener activo
        run: |
          echo "¡Conectado! Entra en remotedesktop.google.com/access"
          sleep 6h
